### ISSUE TITLE
Debian: update repo signature algorithm for xenial and stretch

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/distribution#1]
@vvidic commented on [Fri May 19 2017](https://github.com/perfsonar/toolkit-building/issues/5)

apt in xenial complains about a weak signature in jessie repo:

```
W: http://downloads.perfsonar.net/debian/dists/perfsonar-jessie-snapshot/InRelease: Signature by key 8849D1E81FFEC1081CF66DE31C8650438968F5F6 uses weak digest algorithm (SHA1)
```

This needs to be configured on the Debian repository server.

**Comment by mfeit-internet2** [comment]
This is probably not the right part of GitHub for this ticket.

**Comment by vvidic** [comment]
Repo signature updated to SHA256 and apt does not show warnings or errors anymore.

**Comment by laeti-tia** [comment]
All repos are configured with SHA256 signatures, this can be closed.
